### ISSUE TITLE
Single command to switch from .component and .page

### ISSUE THREAD

**Issue by jugarpeupv** [Everduin94/nvim-quick-switcher#2]
Hi,

First of all thank you for this awesome plugin ^^

I wonder if is it possible to bind a single keymap for switching to html / ts / scss in Angular project independently if we are currently in a .page or .component buffer

Now i have to do it in separate keybindings but it is now efficient

keymap("n", "<leader>oe", "<cmd>:lua require('nvim-quick-switcher').find('.service.ts')<CR>", opts)
keymap("n", "<leader>om", "<cmd>:lua require('nvim-quick-switcher').find('.module.ts')<CR>", opts)
keymap("n", "<leader>os", "<cmd>:lua require('nvim-quick-switcher').find('.component.ts')<CR>", opts)
keymap("n", "<leader>oh", "<cmd>:lua require('nvim-quick-switcher').find('.component.html')<CR>", opts)

keymap("n", "<leader>as", "<cmd>:lua require('nvim-quick-switcher').find('.page.ts')<CR>", opts)
keymap("n", "<leader>ah", "<cmd>:lua require('nvim-quick-switcher').find('.page.html')<CR>", opts)

**Comment by Everduin94** [comment]
Hey thanks for the kind words about the plugin, I appreciate it. :)

Does something like this work for you?
```lua
keymap("n", "<leader>oc", "<cmd>:lua require('nvim-quick-switcher').find('(.+page|.+component).ts', { regex = true })<CR>", opts)
keymap("n", "<leader>ov", "<cmd>:lua require('nvim-quick-switcher').find('(.+page|.+component).html', { regex = true })<CR>", opts)
```

I don't think I've ever used `.page` in an Angular project so I'm not sure what your folder structure looks like. -- The above should jump straight to `.page.ts` or `.component.ts` given there's only one or the other in the folder.

So for example, if you have a structure like below, you'll get a prompt to pick page or component instead of jumping straight to one or the other.

```
Tasks
- tasks.page.ts
- tasks.component.ts
```

**Comment by jugarpeupv** [comment]
It is working! Many thanks! Its because i use ionic and pages end with .page ^^

**Comment by Daerniss** [comment]
What worked for me:
Create a file in plugins folder with any name (quick-switcher.lua for example) and set keys you want
```
return {
  "Everduin94/nvim-quick-switcher",
  keys = {
    {
      "<leader>oo",
      "<cmd>:lua require('nvim-quick-switcher').find('.component.html')<CR>",
      desc = "Open template file",
    },
    {
      "<leader>ou",
      "<cmd>:lua require('nvim-quick-switcher').find('.component.ts')<CR>",
      desc = "Open Component File",
    },
    {
      "<leader>op",
      "<cmd>:lua require('nvim-quick-switcher').find('.module.ts')<CR>",
      desc = "Open Module File",
    },
    {
      "<leader>oy",
      "<cmd>:lua require('nvim-quick-switcher').find('.service.ts')<CR>",
      desc = "Open Service File",
    },
  },
}
```
